name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '14', '16' ]

    steps:
      - uses: actions/checkout@v2

      - uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: sbt -v update compile
      - run: sbt -v test
