name: build-and-test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '14', '16' ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17.0'
          java-package: jdk
          cache: 'sbt'

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: sbt -v update compile
      - run: sbt -v test
